[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
force_eth_gas_price = "0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
